config/routes.rb
CodingTest::Application.routes.draw do
  resources :updates
  root to: "updates#new"
end

app/models/update.rb
require 'CSV'

class Update < ActiveRecord::Base
  has_attached_file :csv_file
  validates_attachment_presence :csv_file
  validates_attachment_content_type :csv_file, :content_type => ['text/csv','text/comma-separated-values','text/csv','application/csv','application/excel','application/vnd.ms-excel','application/vnd.msexcel','text/anytext','text/plain']

  has_many :users, dependent: :destroy

  def create_users_from_batch
    users = []
    erroring_rows = []
    current_row = 1
    user_hash_validator = UserHashValidator.new

    CSV.foreach(self.csv_file.path, headers: true) do |row|
      row = row.to_hash
      errors = user_hash_validator.validate_hash(row).values.flatten
      users.push "('#{row['first_name']}', '#{row['last_name']}', #{row['age']}, '#{row['sex']}', '#{row['personality']}', #{self.id})"  if errors == [nil]
      erroring_rows << current_row unless errors == [nil]
      current_row += 1
    end
    write_users_to_db users
    return erroring_rows
    rescue TypeError => e
      errors.add(:base, "Problem creating users from CSV file")
  end

  private

  def write_users_to_db users
    conn = ActiveRecord::Base.connection
    sql = "INSERT INTO users (first_name, last_name, age, sex, personality, update_id) VALUES #{users.join(', ')}"
    conn.execute sql
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_with UserValidator
  belongs_to :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show]

  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
  end

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
    render text: "Not supported", status: 501
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new update_params

    respond_to do |format|
      if @update.save
        errors = @update.create_users_from_batch
        notice_str = "Update was successfully created."
        notice_str += "Errors found in CSV in rows [#{errors.join(',')}]" unless errors.empty?
        format.html { redirect_to @update, notice: notice_str }
        format.json { render action: 'show', status: :created, location: @update }
      else
        format.html { render action: 'new' }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    render text: "Not supported", status: 501
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    render text: "Not supported", status: 501
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.find(params[:id])
    end

   def update_params
     params[:update].permit(:csv_file)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodingTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/updates/_form.html.erb
<%= form_for(@update) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.file_field :csv_file %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updates/index.html.erb
<h1>Listing updates</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Updated At</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @updates.each do |update| %>
      <tr>
        <td><%= update.id %>
        <td><%= update.updated_at %>
        <td><%= link_to 'Show', update %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Update', new_update_path %>

app/views/updates/new.html.erb
<h1>New update</h1>

<%= render 'form' %>

<%= link_to 'Back', updates_path %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Update <%= @update.id %></h1>
<h2>Uploaded <%= @update.updated_at %></h2>

<h2>Users:</h2>
<div>
<table>
<tr>
  <th>First Name</th>
  <th>Last Name</th>
  <th>Age</th>
  <th>Sex</th>
  <th>Personality</th>
</tr>
<% @update.users.each do |user|%>
  <tr>
    <td><%=user.first_name%></td>
    <td><%=user.last_name%></td>
    <td><%=user.age%></td>
    <td><%=user.sex%></td>
    <td><%=user.personality%></td>
  </tr>
<% end %>
</table>
</div>
<div>
<%= link_to 'Back', updates_path %>
</div>